version: '3.8'
services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  postgres:
    image: postgres:13
    container_name: notiz-api-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    
  redis:
    image: redis:6
    container_name: notiz-api-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
    name: notiz-api-db
  redis:
    name: nest-api-redis