version: '3.8'
services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    
  redis:
    image: redis:6
    container_name: notiz-api-redis
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  mysql:
    name: mysql-db
  redis:
    name: nest-api-redis